on:
  push:
    tags:
      - "[v]?[0-9]+.[0-9]+.[0-9]+" # isolate to tags of the form v1.2.3
  workflow_dispatch:

name: Publish

jobs:
  publish-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: publish
        run: cargo publish --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-binaries:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          # build binaries for every supported platform
          - os: ubuntu-latest
            binary-name: "sire"
            asset-name: "sire" # asset names must be unique within a given release
          - os: macos-latest
            binary-name: "sire"
            asset-name: "sire_mac" # asset names must be unique within a given release
          - os: windows-latest
            binary-name: "sire.exe"
            asset-name: "sire.exe" # asset names must be unique within a given release

    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.job.os }}
        run: cargo build --verbose --release
      - name: Release ${{ matrix.job.os }}
        # plugin docs: https://github.com/marketplace/actions/upload-files-to-a-github-release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/${{ matrix.job.binary-name }}
          asset_name: ${{ matrix.job.asset-name }}
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
